// 4SPAFrameworks/vue_intro/src/components/Loader.vue
<template>
  <div class="loader initial" v-show="loading">
    <div class="spinner">
      <div class="spinner-circle"></div>
      <div class="spinner-circle"></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Loader',
  props: {
    loading: {
      type: Boolean,
      required: true
    }
  },
}
</script>

// 5.1SPAFrameworks/react_intro/src/components/Loader/Loader.js
import './loader.scss';

const Loader = (props) => {

  if(!props.loading){
    return null;
  }

  return (
    <div className="loader initial">
      <div className="spinner">
        <div className="spinner-circle"></div>
        <div className="spinner-circle"></div>
      </div>
    </div>
  );
}

export default Loader;
