// 4SPAFrameworks/angular-intro/src/app/loader/loader.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-loader',
  templateUrl: './loader.component.html',
  styleUrls: ['./loader.component.scss']
})
export class LoaderComponent implements OnInit {

  @Input() loading: boolean;

  constructor() { }
  
  ngOnInit(): void {
  }

}

<div class="loader initial" *ngIf="loading">
  <div class="spinner">
    <div class="spinner-circle"></div>
    <div class="spinner-circle"></div>
  </div>
</div>

// 5.1SPAFrameworks/react_intro/src/components/Loader/Loader.js
import './loader.scss';

const Loader = (props) => {

  if(!props.loading){
    return null;
  }

  return (
    <div className="loader initial">
      <div className="spinner">
        <div className="spinner-circle"></div>
        <div className="spinner-circle"></div>
      </div>
    </div>
  );
}

export default Loader;
