// 5.1SPAFrameworks/angular-intro/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { TeamService } from './services/team.service';
import { Team } from './services/Team';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-intro';
  hrsMinSec = {hours: 0, minutes: 2, seconds: 10};
  loading = true;
  teams: Array<Team> = [];
  
  constructor(private teamService: TeamService) { }
  
  ngOnInit(): void {
    setTimeout(() => { this.loading = false; }, 5000)

    this.teamService.getAllTeams().subscribe( data => {
      console.log(data.message);
      this.teams = data.message;
    });
  }

}

<div class="container-fluid">
  <div class="row">
    <div class="leaderboard">
      <span class="leaderboard-corner-one"></span>
      <span class="leaderboard-corner-two"></span>
  

      <div class="leaderboard-inner">
        <p class="title mt-6">Programming Escape Room</p>

        <p class="subtitle mt-6">FH Campus Wien</p>
        
        <app-timer-component id="timer" [hrsMinSec]="hrsMinSec" class="row mt-6 mb-6">
        </app-timer-component>

        <div class="row mt-4">
            <app-leaderboard [teams]="teams">
            </app-leaderboard>
        </div>
        
        <app-loader [loading]="loading"></app-loader>

      </div>
    </div>
  </div>
</div>

// 5.1SPAFrameworks/react_intro/src/App.js
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import './styles/leaderboard.scss'; 
import Timer from './components/Timer/Timer';
import Loader from './components/Loader/Loader';
import Leaderboard from './components/Leaderboard/Leaderboard';
import React, { useState, useEffect } from 'react';
import { getAllTeams } from './services/team.service';

function App() {
  const hoursMinSecs = {hours: 0, minutes: 0, seconds: 10} // countdown time
  const [loading, setLoading] = useState(true); // whether async request is still going on
  const [teams, setTeams] = useState([]); // teams for leaderboard

  const [messageText, setMessageText] = useState("");

  const sortTeams = (list) => {
    list.sort((a, b) => {
      return a.progress - b.progress;
    });
  }

  useEffect(() => {
    async function fetchTeams() {
      let response = await getAllTeams();

      if(response.length > 0){
        sortTeams(response);
        setTeams(response);
      }
      
      setLoading(false);
    }

    fetchTeams()
  }, [])

  return (
    <Container fluid>
      <Row>
        <div className="leaderboard">
          <span className="leaderboard-corner-one"></span>
          <span className="leaderboard-corner-two"></span>

          <div className="leaderboard-inner">
            <Row>
              <span className="title">Programming Escape Room</span>
            </Row>
            <Row>
              <span className="subtitle">FH Campus Wien</span>
            </Row>
 
            <Timer hoursMinSecs={hoursMinSecs} timeText="Time remaining..."></Timer>

            <Row className="mt-4">
                {/** TODO make Component */}
                <Leaderboard teams={teams}/>
            </Row>

            <Loader loading={loading}></Loader>

          </div>
        </div>
      </Row>
      <div className="bg-custom"></div>
    </Container>
  );
}

export default App;
